Lab3
chichaparadise/front pull request #3
Opened 2022-05-02 18:09 UTC by chichaparadise

2022-05-16 14:04 UTC, katetushkan requested changes

2022-05-16 14:04 UTC, katetushkan commented on css/style.css
> +.product__button{
smth went wrong with naming...

2022-05-16 14:04 UTC, katetushkan commented on login.html
> +        <div class="auth">
maybe `section`?

2022-05-16 14:04 UTC, katetushkan commented on index.html
> +                <div class="personalInfo">
section maybe?

2022-05-16 14:04 UTC, katetushkan commented on index.html
> +                <h1 class="productDetails__title">NITE JOGGER</h1>
only one `h1` an be on page

2022-05-16 14:04 UTC, katetushkan commented on index.html
> +                <h3 class="menu__item">Adidas</h3>
`h3` only applicable for section's or document's headers

2022-05-17 07:59 UTC, chichaparadise commented on css/auth.css
> +    margin-top: 10%;
fixed

2022-05-17 08:02 UTC, chichaparadise commented on login.html
> +        <div class="auth">
changed to `section`

2022-05-17 08:02 UTC, chichaparadise commented on index.html
> +                <h3 class="footerMenu__title">Products</h1>
substituted with `<p>`

2022-05-17 08:03 UTC, chichaparadise commented on index.html
> +                <div class="personalInfo">
replaced with `article`

2022-05-17 08:05 UTC, chichaparadise commented on index.html
> +                <h1 class="productDetails__title">NITE JOGGER</h1>
regardless there are 5 of h1 tags, these are slider items, so there will be only one h1 element per page

2022-05-17 08:05 UTC, chichaparadise commented on index.html
> +                <h3 class="menu__item">Adidas</h3>
replaced with `<p>`

2022-05-17 08:06 UTC, chichaparadise commented on index.html
> +                </div>
fixed

2022-05-17 08:08 UTC, chichaparadise commented
followed your tips and fixed issues, hope you will be satisfied)))

2022-05-17 12:30 UTC, katetushkan requested changes

2022-05-17 12:30 UTC, katetushkan commented on index.html
> +                <h2 class="productDetails__title">NITE JOGGER</h2>
See, There is a rule, so the page/section can has only one header. Also, u can't use lower headers without higher ones. For example, u can't use `h2` without `h1`. Or use `h1` and `h3` with skipping `h2`. If u use cards and use `<h...>` tags in header so u can still stick to the rules of the ``article`'s area and start with the high order heading.

2022-05-17 12:53 UTC, katetushkan requested changes
Mobile version ?

2022-05-17 12:57 UTC, chichaparadise commented
what's wrong with is?

2022-05-17 14:41 UTC, chichaparadise commented
Oh, I've recently discovered that responce differs in inspection mode and original browsing, I'll fix it A$AP

2022-05-19 09:49 UTC, merged